{% set version = "0.9-52" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-penalized
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/penalized_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/penalized/penalized_{{ version }}.tar.gz
  sha256: d8e38e6c4e993c74998ca8f986b4e11e09c0b9971103e1d5c7ebdee75f6d6a21

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-survival
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-survival

test:
  commands:
    - $R -e "library('penalized')"           # [not win]
    - "\"%R%\" -e \"library('penalized')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=penalized
  license: GPL-2.0-or-later
  summary: Fitting possibly high dimensional penalized regression models. The penalty structure can be any combination of an L1 penalty (lasso and fused lasso), an L2 penalty (ridge) and a positivity constraint on the regression coefficients. The supported regression models are linear, logistic and Poisson regression and
    the Cox Proportional Hazards model. Cross-validation routines allow optimization of the tuning parameters.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
