{% set version = "0.9-51" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-penalized
  version: {{ version|replace("-", "_") }}

source:
  fn: penalized_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/penalized_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/penalized/penalized_{{ version }}.tar.gz
  sha256: be09693cf00d721b79ef32fadd7955a0e958217ad4cf08a4ddfc27ab5a545bbb

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-survival

  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-survival

test:
  commands:
    - $R -e "library('penalized')"  # [not win]
    - "\"%R%\" -e \"library('penalized')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=penalized
  license: GPL (>= 2)
  summary: Fitting possibly high dimensional penalized regression models. The penalty structure
    can be any combination of an L1 penalty (lasso and fused lasso), an L2 penalty (ridge)
    and a positivity constraint on the regression coefficients. The supported regression
    models are linear, logistic and Poisson regression and the Cox Proportional Hazards
    model. Cross-validation routines allow optimization of the tuning parameters.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
