travis:
  secure:
    BINSTAR_TOKEN: MGd2z5+xExxo7ajV6Kx4pGKZhYCEayk1r/IrNoGVt6uoHUQYhycoyU9esZ+tJqlCl3RN4fhi/dziuGT7ohk77AGJnkvdJRCcyp/vgnFH8cc4MbpvQTt18i5ENshsLExl/TnhIYFtjtfKi9xCHGYFCjLN60o9rqHDa8CIjnjTniIGUKB+pLPtx9No/EdBIHPZUJJrdc2uafawHhuzg/rIJzFARwXMH7rTbmZL4ppGw5OOhqKxXh/qXmtq4G8iUvDiz5nQuDjz3vHVVSVfblEi/CZJJ2v3UGlWOeKpnTjxTYvrFsyt0mcI0PU0BNc+JhPKHgsjLPG2l881N1d9EsGMfxcmDrklX5bvxpGrXDc5kCu3dQEe0SI+eYsN7iIKb4ic+2M06rKu0Uz+dbDb7Q6g7sGDHBjV5e+fdMZd7UnHNPgSxvTqY7IxbaXvqTFRIeeJP/C4PC4U7xCVfFi6U4zmiq/wAtOiVqziVsApwZ7wEQ6KmZJ4ERJ4Z6zH+TA4/uZeSqX9bRUngZlq1dAuP8ZAtM18AyqSZhalL41IolgajIwTAW9FjOUIj6THEmLHEE4cGAmIsLbxWh8H3XYG0fDcgNbt8t/ZByR2KGUgBUY4Kj0ebiaUk3Q8ru1F7PD0BIJJAtj5lGeAhlkt8Q3v/AteUkQ7B8v0xqIm7kiwVAMyRV4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
