appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CXwTXUNKi6u5CXwCaMARaBY+B95UlyrTbaYI6Ub2Z6Tl6mDykqHoNZS5clfMjNbUi/sqCcd/kn+ToznwdvASwd4loYOWqn3L6BUHW89uV5jjZ1/eOirhbG6ALJIeF4f54ZarkCw3x6+MQI+Bhhn6R08P1v7W2YVLZK5wCsxtxEDmOloM5oacVzkGgtNeIZF3YvWZzZfepWzguCWtagrSdtQY/1M3/nvTmdTVwUd0IeowGfKyeyWsW40cko0s5nOreG2eLgAOhwMJnte33m5tqD8TO5meoxLDaYZx1d5D/SqHvu93DPBUZloUwn/eBymiuiAGdgyKnN6ivLrPoQzHTA2yXaa8Xt+l12sou9JqxFRJ57/zhLhlTWK0oIvpt9rhKjMUVk6L3sXnV7gL700ZpMvresIQYkQkHoU75wBt1aOXwi+Ed6eOebE/vWHslmfgfDo23lAE+18fTCKoHek4TstZLNQqqot2U/9V7sZRfQIQIaBgKVkoqFmqtepjXRs4JONeXnPBTB24OHTog0hEMqW5t2Mk9ENcJDkOAgwl5uDMwbOvtaRmHtxeg74gMtzMIZIo9EAHA7UPVyDndaFb/EUPz9a32xpwOGp8Lxhgvom9EzcF4H7NHyHCT3/9rHeiYmihOw+zT06lyx0BxpymOlnu8l5YRcqcm9NkqaBVBUs=}
